print('Olá, Mundo')
print('Tudo bem?')
print('Olha meu texto')
print('Minha casa')
print('Bora jogar basquete')
print('Isso é bem fácil')
print('Aperta control s')
print('Respira e vai dormir')
print('tô morrendo de sono')
print('Vai São Paulo')